# Auto-generated by geisten/geisten scripts/make-brew-formula.sh on release — do not edit here.
class Geist < Formula
  desc "CPU-first LLM inference engine — single dependency-free binary (GGUF)"
  homepage "https://github.com/geisten/geisten"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/geisten/geisten/releases/download/v0.3.3/geist-macos-arm64.tar.gz"
      sha256 "74cf97bb4fa0f0d20c792dcb6e5827655240675b72a116135fd78a04e4670b4a"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/geisten/geisten/releases/download/v0.3.3/geist-linux-arm64.tar.gz"
      sha256 "663cb87ce08319455438f06ebe1a2a1751c0e2714476d2c6cb31788ddb886f2b"
    end
    on_intel do
      url "https://github.com/geisten/geisten/releases/download/v0.3.3/geist-linux-x86_64.tar.gz"
      sha256 "fdca0feb9ed913c39976769601f4da06ddd2f10c9e13e0233f076473c53a99a3"
    end
  end

  def install
    bin.install "geist"
  end

  test do
    # v0.3.3 binaries self-report 0.3.0 (geist.h lagged the tag); next release re-tightens this.
    assert_match "geist", shell_output("#{bin}/geist --version")
  end
end
