# Auto-generated by geisten/geistlib scripts/make-brew-formula.sh on release — do not edit here.
class Geist < Formula
  desc "CPU-first LLM inference engine — single dependency-free binary (GGUF)"
  homepage "https://github.com/geisten/geistlib"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/geisten/geistlib/releases/download/v0.4.0/geist-macos-arm64.tar.gz"
      sha256 "47678006603bbb680a55564cd76cdd7b9f62ad66d2f1355ebadb0c3ac7fbab97"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/geisten/geistlib/releases/download/v0.4.0/geist-linux-arm64.tar.gz"
      sha256 "cb8386561c9aa1ca420ba106d9aed9a164a480c2b52551a0b334c6e07e9856a9"
    end
    on_intel do
      url "https://github.com/geisten/geistlib/releases/download/v0.4.0/geist-linux-x86_64.tar.gz"
      sha256 "594da46c557ec808dea8a267e5a5336f3a86a7e4946342998fbc483d9b6a7d18"
    end
  end

  def install
    bin.install "geist"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/geist --version")
  end
end
