# Generated by geisten/geist-serve scripts/bump-tap.sh — do not edit here.
class GeistServe < Formula
  desc "One local GGUF model behind the Ollama and OpenAI APIs (geist engine)"
  homepage "https://github.com/geisten/geist-serve"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/geisten/geist-serve/releases/download/v0.1.0/geist-serve-macos-arm64"
      sha256 "5c2396a7293fedb3e6ba34e937f224806d6eeb86e079e2fe0a342b56c147d406"
    end
  end
  on_linux do
    on_intel do
      url "https://github.com/geisten/geist-serve/releases/download/v0.1.0/geist-serve-linux-x86_64"
      sha256 "90939cda947504b251c66ca4a6d717849d261f043496b4616ec374e6100bbb26"
    end
    on_arm do
      url "https://github.com/geisten/geist-serve/releases/download/v0.1.0/geist-serve-linux-aarch64"
      sha256 "b337ef97a5ed2504ce62cf06f2b16d8ce67c997851084f9c5b0754e9015f0cb2"
    end
  end

  def install
    bin.install Dir["geist-serve-*"].first => "geist-serve"
    # brew services runs this wrapper: it reads the model path (and optional
    # flags on a second line) from etc/geist-serve/model, the one file a
    # user edits. Same idea as /etc/default/geist-serve under systemd.
    (bin/"geist-serve-service").write <<~SH
      #!/bin/sh
      conf="#{etc}/geist-serve/model"
      [ -s "$conf" ] || { echo "geist-serve: put the GGUF path into $conf (see brew info geist-serve)" >&2; exit 78; }
      model=$(sed -n 1p "$conf"); flags=$(sed -n 2p "$conf")
      exec "#{opt_bin}/geist-serve" "$model" $flags
    SH
    (etc/"geist-serve").mkpath
  end

  service do
    run [opt_bin/"geist-serve-service"]
    keep_alive true
    log_path var/"log/geist-serve.log"
    error_log_path var/"log/geist-serve.log"
    environment_variables OMP_WAIT_POLICY: "active"
  end

  def caveats
    <<~EOS
      Tell the service which model to serve (first line: GGUF path, optional
      second line: flags such as --host 0.0.0.0), then start it:
        echo /path/to/model.gguf > #{etc}/geist-serve/model
        brew services start geist-serve
        curl http://127.0.0.1:11434/api/tags
      Without the service: geist-serve /path/to/model.gguf
    EOS
  end

  test do
    assert_match "usage", shell_output("#{bin}/geist-serve 2>&1", 2)
  end
end
