# Generated by geisten/geist-serve scripts/bump-tap.sh — do not edit here.
class GeistServe < Formula
  desc "One local GGUF model behind the Ollama and OpenAI APIs (geist engine)"
  homepage "https://github.com/geisten/geist-serve"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/geisten/geist-serve/releases/download/v0.2.1/geist-serve-macos-arm64"
      sha256 "b1a4862aa75ead70fbc07352e107f9ee023daf332f09750269d7269bddd9a607"
      resource "geistd" do
        url "https://github.com/geisten/geist-serve/releases/download/v0.2.1/geist-serve-macos-arm64-geistd"
        sha256 "21c7eb5e72a90e3597696c6d17817ba54eb191b917b3c85d04ed3da566b107d6"
      end    end
  end
  on_linux do
    on_intel do
      url "https://github.com/geisten/geist-serve/releases/download/v0.2.1/geist-serve-linux-x86_64"
      sha256 "571e74115fd428469b26bdd8ed7d73c01bd560e9a7e356be20dc2ebd9615c378"
      resource "geistd" do
        url "https://github.com/geisten/geist-serve/releases/download/v0.2.1/geist-serve-linux-x86_64-geistd"
        sha256 "b925f4da9576a808671d36473ebd5e6c66e725abdb1f5a1fbd7a732b636edff7"
      end    end
    on_arm do
      url "https://github.com/geisten/geist-serve/releases/download/v0.2.1/geist-serve-linux-aarch64"
      sha256 "57e704fbc6313d436527e705202f3186db7809fc14d8ece9a85951b34a8ffbb3"
      resource "geistd" do
        url "https://github.com/geisten/geist-serve/releases/download/v0.2.1/geist-serve-linux-aarch64-geistd"
        sha256 "fc86193083dfebcfd2d13e00c51216bef70d53c4d96df8f9122060268b994c1b"
      end    end
  end

  def install
    bin.install Dir["geist-serve-*"].reject { |f| f.end_with?("-geistd") }.first => "geist-serve"
    resource("geistd").stage { bin.install Dir["geist-serve-*-geistd"].first => "geistd" } if resources.any? { |r| r.name == "geistd" }
    # brew services runs this wrapper: it reads the model path (and optional
    # flags on a second line) from etc/geist-serve/model, the one file a
    # user edits. Same idea as /etc/default/geist-serve under systemd.
    (bin/"geist-serve-service").write <<~SH
      #!/bin/sh
      conf="#{etc}/geist-serve/model"
      [ -s "$conf" ] || { echo "geist-serve: put the GGUF path into $conf (see brew info geist-serve)" >&2; exit 78; }
      model=$(sed -n 1p "$conf"); flags=$(sed -n 2p "$conf")
      exec "#{opt_bin}/geist-serve" "$model" $flags
    SH
    (etc/"geist-serve").mkpath
  end

  service do
    run [opt_bin/"geist-serve-service"]
    keep_alive true
    log_path var/"log/geist-serve.log"
    error_log_path var/"log/geist-serve.log"
    environment_variables OMP_WAIT_POLICY: "active"
  end

  def caveats
    <<~EOS
      Tell the service which model to serve (first line: GGUF path, optional
      second line: flags such as --host 0.0.0.0), then start it:
        echo /path/to/model.gguf > #{etc}/geist-serve/model
        brew services start geist-serve
        curl http://127.0.0.1:11434/api/tags
      Without the service: geist-serve /path/to/model.gguf
    EOS
  end

  test do
    assert_match "usage", shell_output("#{bin}/geist-serve 2>&1", 2)
  end
end
